"""Game constants."""

from pathlib import Path

_PACKAGE_DIR = Path(__file__).resolve().parent

TICK_MS = 100
UI_REFRESH_MS = 100
FUEL_DRAIN_PER_NODE = 0.15
TIREDNESS_PER_RIDE = 20.0
REST_TICKS = 50
RIDE_EXPIRY_TICKS = 150
MAX_MISSED_PER_DAY = 3
BASE_RIDES_PER_DAY = 3
RIDES_PER_EXTRA_CAB = 2
MAX_RIDES_PER_DAY = 14
TICKS_PER_NODE = 5
DAY_START_GRACE_TICKS = 60
DAY_ONE_GRACE_TICKS = 150
DAY_ONE_SPAWN_INTERVAL_MULT = 2
CAB_COST = 120.0
BASE_FARE = 15.0
FARE_PER_KM = 3.0
VIP_BASE_FARE = 35.0
VIP_FARE_PER_KM = 8.0
VIP_MIN_NODES = 16
BASIC_MAX_NODES = 30
VIP_SPAWN_CHANCE = 0.28
DAY_DURATION_TICKS = 600
GRAPH_FILE = str(_PACKAGE_DIR / "assets" / "tbilisi_graph.graphml")
TBILISI_PLACE = "Tbilisi, Georgia"
UPGRADE_COSTS = {"fuel_tank": 70, "stamina": 50, "speed": 80}
REFUEL_COST = 15.0
DB_FILE = str(_PACKAGE_DIR.parent / "graphcabs.db")
